User.destroy_all
p "Destroyed !"

simon = User.create(nickname: "simoncharbonnier", email: "simoncharbonnier@orange.fr", password: "secret")
valentin = User.create(nickname: "valdrn", email: "valdrn@gmail.com", password: "secret")
fabien = User.create(nickname: "drptitlu", email: "drptitlu@gmail.com", password: "secret")
herve = User.create(nickname: "criaudh", email: "criaudh@gmail.com", password: "secret")
sebastien = User.create(nickname: "ssaunier", email: "ssaunier@gmail.com", password: "secret")
nicolas = User.create(nickname: "nfilzi", email: "nfilzi@gmail.com", password: "secret")
unknown = User.create(nickname: "xastiro", email: "xastiro@gmail.com", password: "secret")

post1 = Post.create(user: simon, title: "post 1", content: "content post 1", url: "www.urllambda.com")
post2 = Post.create(user: valentin, title: "post 2", content: "content post 2", url: "www.urllambda.com")
post3 = Post.create(user: valentin, title: "post 3", content: "content post 3", url: "www.urllambda.com")
post4 = Post.create(user: fabien, title: "post 4", content: "content post 4", url: "www.urllambda.com")
post5 = Post.create(user: herve, title: "post 5", content: "content post 5", url: "www.urllambda.com")
post6 = Post.create(user: sebastien, title: "post 6", content: "content post 6", url: "www.urllambda.com")
post7 = Post.create(user: nicolas, title: "post 7", content: "content post 7", url: "www.urllambda.com")
post8 = Post.create(user: nicolas, title: "post 8", content: "content post 8", url: "www.urllambda.com")
post9 = Post.create(user: unknown, title: "post 9", content: "content post 9", url: "www.urllambda.com")
post10 = Post.create(user: unknown, title: "post 10", content: "content post 10", url: "www.urllambda.com")

Comment.create(user: nicolas, post: post1, content: "super nice !")
Comment.create(user: valentin, post: post1, content: "merci !")
Comment.create(user: herve, post: post1, content: "super nice !")
Comment.create(user: unknown, post: post1, content: "merci !")
Comment.create(user: fabien, post: post2, content: "super nice !")
Comment.create(user: simon, post: post3, content: "merci !")
Comment.create(user: nicolas, post: post3, content: "super nice !")
Comment.create(user: sebastien, post: post3, content: "merci !")
Comment.create(user: herve, post: post4, content: "super nice !")
Comment.create(user: valentin, post: post4, content: "merci !")
Comment.create(user: unknown, post: post5, content: "super nice !")
Comment.create(user: simon, post: post6, content: "merci !")
Comment.create(user: fabien, post: post7, content: "super nice !")
Comment.create(user: herve, post: post7, content: "merci !")
Comment.create(user: sebastien, post: post7, content: "super nice !")
Comment.create(user: simon, post: post8, content: "merci !")
Comment.create(user: nicolas, post: post8, content: "super nice !")
Comment.create(user: valentin, post: post9, content: "merci !")
Comment.create(user: fabien, post: post9, content: "super nice !")
Comment.create(user: sebastien, post: post10, content: "super nice !")
p "Created !"
